### ISSUE TITLE
release your model

### ISSUE THREAD

**Issue by guchengxi1994** [mosix11/Face2Bitmoji#1]
hello there,
   this work is impressing, if  it's convenient ,can you release your LACycleGAN model for testing ?

**Comment by guchengxi1994** [comment]
and it went wrong when i ran the train.py

```
Traceback (most recent call last):
  File ".\train.py", line 252, in <module>
    A_lm_reg = keras.models.load_model(config.A_LANDMARK_REGRESSOR_PATH)
  File "D:\anaconda\envs\tf2\lib\site-packages\tensorflow\python\keras\saving\save.py", line 211, in load_model
    loader_impl.parse_saved_model(filepath)
  File "D:\anaconda\envs\tf2\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 114, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: ./landmark_regressor/celeba_lmreg_heat/{saved_model.pbtxt|saved_model.pb}
```

is there some files missing?
